### ISSUE TITLE
Event text not visible in dark mode

### ISSUE THREAD

**Issue by tonywhitmore** [pulsejet/banner-ics#10]
Hi, the text accompanying the event information is not visible when Roundcube is running in dark mode. It looks OK in light mode. In dark mode the text is there if you highlight it. I have (I hope) attached a screenshot below.

![Screenshot from 2023-01-18 15-27-41](https://user-images.githubusercontent.com/28754035/213213618-ed757171-9158-4e0f-b59d-94a8ab958999.png)

**Comment by kbzowski** [comment]
+1

**Comment by tonywhitmore** [comment]
I have found that adding a "color" statement the CSS file can be used to change the text colour to the same as the rest of the UI in "dark mode". However, this is only useful if you never or rarely use light mode, as the resulting text is hard to read in light mode. There must be a better way to do this though!

The amended CSS is below.

`.ics-event {
    display: block !important;
    font-size: 0.9em;
    color: #c5d1d3;
}
`

**Comment by gotspatel** [comment]
@tonywhitmore 

Refer #7  I think this solves it

**Comment by tonywhitmore** [comment]
Thanks, I have tested the patch and it does indeed seem to resolve the issue. The text in the event banner is clearly visible now in both light and dark modes.

**Comment by pulsejet** [comment]
Should be fixed with 1.3.2 courtsey @harryyoud
