### ISSUE TITLE
Accept Event not Working

### ISSUE THREAD

**Issue by hinermat** [pulsejet/banner-ics#8]
I've installed the plugin per the instructions.  At first glance it seems to work perfectly.  However when I go to accept a meeting invitation I get an error of "no calendar selected" even though I do have a calendar created.

Any thoughts?
![Screenshot 2022-06-17 at 09-58-56 Roundcube Webmail Inbox](https://user-images.githubusercontent.com/107077226/174313249-adb98a9e-440c-4352-9eb2-1707008b052c.png)

**Comment by pulsejet** [comment]
What accept button is this? Can you share a screeenshot?
Probably not a part of this plugin; this plugin only displays a banner like the readme shows
